---
permalink: performance-checker/concept_metrocluster_configuration_verification.html 
sidebar: sidebar 
keywords: metrocluster, configuration, verification 
summary: Vous pouvez éviter les problèmes de performances des charges de travail en miroir dans une configuration MetroCluster en vous assurant que la configuration MetroCluster est correctement configurée. Vous pouvez également améliorer les performances des charges de travail en modifiant la configuration ou en mettant à niveau des composants logiciels ou matériels. 
---
= Vérification de la configuration MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez éviter les problèmes de performances des charges de travail en miroir dans des configurations MetroCluster sur FC et IP en vous assurant que la configuration MetroCluster est correctement configurée. Vous pouvez également améliorer les performances des charges de travail en modifiant la configuration ou en mettant à niveau des composants logiciels ou matériels.

Reportez-vous au https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentation MetroCluster"] pour obtenir les instructions de configuration des clusters dans la configuration MetroCluster, y compris les commutateurs Fibre Channel (FC), les câbles et les liens ISL (Inter-switch Links). Il permet également de configurer le logiciel MetroCluster de sorte que les clusters locaux et distants puissent communiquer avec les données de volume en miroir. Pour obtenir des informations spécifiques à votre configuration MetroCluster sur IP, reportez-vous àla section https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installez une configuration MetroCluster IP"].

Vous pouvez comparer votre configuration MetroCluster aux exigences du https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentation MetroCluster"] afin de déterminer si une modification ou une mise à niveau des composants de votre configuration MetroCluster peut améliorer les performances des workloads. Cet comparatif peut vous aider à répondre aux questions suivantes :

* Les contrôleurs sont-ils adaptés à vos charges de travail ?
* Devez-vous mettre à niveau vos bundles ISL vers une bande passante plus importante pour gérer davantage de débit ?
* Pouvez-vous régler les crédits tampon à tampon (BBC) de vos commutateurs pour augmenter la bande passante ?
* Si vos charges de travail disposent d'un débit d'écriture élevé vers le stockage SSD, devez-vous mettre à niveau vos ponts FC-SAS pour prendre en charge le débit ?


*Informations connexes*

* Pour plus d'informations sur le remplacement ou la mise à niveau des composants MetroCluster, reportez-vous au https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentation MetroCluster"] .
* Pour plus d'informations sur la mise à niveau des contrôleurs, reportez-vous aux sections https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Mise à niveau des contrôleurs d'une configuration FC MetroCluster à l'aide du basculement et du rétablissement"] et https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html["Mise à niveau des contrôleurs d'une configuration IP MetroCluster à l'aide du basculement et du rétablissement"]

