---
permalink: storage-mgmt/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux host 
summary: 'Si vous avez alloué un espace disque insuffisant au `/opt/netapp/data` répertoire pour prendre en charge Unified Manager lors de la configuration initiale de l"hôte Linux, puis de l"installation d"Unified Manager, vous pouvez ajouter de l"espace disque après l"installation en augmentant l"espace disque sur le `/opt/netapp/data` répertoire.' 
---
= Ajout d'espace au répertoire de données de l'hôte Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez alloué un espace disque insuffisant au `/opt/netapp/data` répertoire pour prendre en charge Unified Manager lors de la configuration initiale de l'hôte Linux, puis de l'installation d'Unified Manager, vous pouvez ajouter de l'espace disque après l'installation en augmentant l'espace disque sur le `/opt/netapp/data` répertoire.

*Ce dont vous aurez besoin*

Vous devez avoir un accès utilisateur root à la machine Red Hat Enterprise Linux ou CentOS Linux sur laquelle Unified Manager est installé.

Nous vous recommandons de sauvegarder la base de données Unified Manager avant d'augmenter la taille du répertoire de données.

.Étapes
. Connectez-vous en tant qu'utilisateur root à la machine Linux sur laquelle vous souhaitez ajouter de l'espace disque.
. Arrêtez le service Unified Manager et le logiciel MySQL associé dans l'ordre indiqué : `systemctl stop ocieau ocie mysqld`
. Créez un dossier de sauvegarde temporaire (par exemple `/backup-data`, ) avec suffisamment d'espace disque pour contenir les données dans le répertoire actuel `/opt/netapp/data`.
. Copiez le contenu et la configuration des privilèges du répertoire existant `/opt/netapp/data` dans le répertoire des données de sauvegarde :
+
`cp -arp /opt/netapp/data/* /backup-data`

. Si se Linux est activé :
+
.. Obtenir le type se Linux pour les dossiers dans un dossier existant `/opt/netapp/data` :
+
`se_type=`ls -Z /opt/netapp/data| awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
Le système renvoie une confirmation similaire à ce qui suit :

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. Lancer `chcon` la commande pour définir le type se Linux du répertoire de sauvegarde :
+
`chcon -R --type=mysqld_db_t /backup-data`



. Supprimez le contenu du `/opt/netapp/data` répertoire :
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. Augmentez la taille du `/opt/netapp/data` répertoire à un minimum de 150 Go via des commandes LVM ou en ajoutant des disques supplémentaires.
+
[NOTE]
====
Si vous avez créé `/opt/netapp/data` à partir d'un disque, vous ne devez pas essayer de monter en `/opt/netapp/data` tant que partage NFS ou CIFS. Parce que, dans ce cas, si vous essayez d'étendre l'espace disque, certaines commandes LVM, telles que `resize` et `extend` peuvent ne pas fonctionner comme prévu.

====
. Vérifiez que le `/opt/netapp/data` propriétaire du répertoire (mysql) et le groupe (root) sont inchangés :
+
`ls -ltr /opt/netapp/ | grep data`

+
Le système renvoie une confirmation similaire à ce qui suit :

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. Si se Linux est activé, vérifiez que le contexte du `/opt/netapp/data` répertoire est toujours défini sur mysqld_db_t:
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
Le système renvoie une confirmation similaire à ce qui suit :

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. Supprimez le fichier `abc` afin que ce fichier étranger ne provoque pas d'erreur de base de données à l'avenir.
. Copiez le contenu de `backup-data` retour vers le répertoire développé `/opt/netapp/data` :
+
`cp -arp /backup-data/* /opt/netapp/data/`

. Si se Linux est activé, exécutez la commande suivante :
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. Démarrez le service MySQL :
+
`systemctl start mysqld`

. Une fois le service MySQL démarré, démarrer les services ocie et ocieau dans l'ordre indiqué:
+
`systemctl start ocie ocieau`

. Une fois tous les services démarrés, supprimez le dossier de sauvegarde `/backup-data` :
+
`rm -rf /backup-data`


